### PR TITLE
test(map): standardise `map.jinja` verification

### PR DESCRIPTION
**Pull request by myii**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

UPDATE:
* Follows-on from #68
* Automated using myii/ssf-formula#281

~https://github.com/saltstack-formulas/sudoers-formula/pull/65#issuecomment-681046505~
~https://github.com/saltstack-formulas/openssh-formula/pull/193~

### Describe the changes you're proposing

Discussion in Slack: https://freenode.logbot.info/saltstack-formulas/20200826#c4886021-c4887283.

* https://docs.chef.io/inspec/resources/yaml/

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@daks Realised I could use `it` rather than introducing a top-level key:

* https://travis-ci.org/github/myii/sudoers-formula/jobs/721500088#L1686-L1722

Then it was a matter of figuring out how to grab the `params`, which I found here:

* https://github.com/inspec/inspec/issues/2036#issuecomment-327316670
* https://github.com/inspec/inspec/issues/3738#issuecomment-457454764

**Comment by daks** [comment]
Good job @myii :) At a side note, I recently upgraded to Inspec4 and we use the `inputs` (https://docs.chef.io/inspec/inputs/) which may also be a solution to provide data to inspec. Not sure if it could be used instead of this solution and if that would be more convenient or less.

**Review by daks — APPROVED** [review]

**Comment by myii** [comment]
Repurposed this PR with all of the standardisations worked out across the various formulas.

**Comment by myii** [comment]
Self-merging since tests only.

**Pull request merged**
